- name: fish
  package:
    name:
      - fish
    state: present
  become: yes

- name: fish dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ fish_cfg_dir }}"
    - "{{ fish_cfg_dir }}/functions"

- name: fish cfg
  copy:
    src: config.fish
    dest: "{{ fish_cfg_dir }}/config.fish"

- name: fish funs
  copy:
    src: "{{ item }}"
    dest: "{{ fish_cfg_dir }}/functions/{{ item }}"
  loop:
    - text_to_color.fish
    - prompt_dmr.fish
    - prompt_right_dmr.fish

- name: more fish funs
  copy:
    src: "functions/{{ item }}"
    dest: "{{ fish_cfg_dir }}/functions/{{ item }}"
  loop:
    - fish_title.fish

- name: more fish cfg
  copy:
    src: "conf.d/{{ item }}"
    dest: "{{ fish_cfg_dir }}/conf.d/{{ item }}"
  loop:
    - env_unconditional.fish

- name: fish complete
  copy:
    src: "completions/{{ item }}"
    dest: "{{ fish_cfg_dir }}/completions/{{ item }}"
  loop:
    - screen.fish
